# Generated by Django 3.2.5 on 2022-06-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_wool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='woolitem',
            name='name',
        ),
        migrations.AddField(
            model_name='woolitem',
            name='brand_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='woolitem',
            name='product_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='woolitem',
            name='composition',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='woolitem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
