# Generated by Django 3.2.5 on 2022-06-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_wool', '0002_auto_20220626_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='woolitem',
            old_name='brand_name',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='woolitem',
            old_name='product_name',
            new_name='product',
        ),
    ]
