# Generated by Django 3.2.5 on 2022-06-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_wool', '0003_auto_20220626_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woolitem',
            name='needle_size',
            field=models.CharField(default='$', max_length=100),
        ),
    ]
