# Generated by Django 3.2.5 on 2022-06-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_wool', '0004_alter_woolitem_needle_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='woolitem',
            name='link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
